spring.application.name=payvault-backend

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:payvaultdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (accessible at /h2-console)
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

# Ensure schema.sql runs first, then data.sql
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Server
server.port=8080

# CORS
app.cors.allowed-origins=https://spring-boot-payvault.vercel.app/
